#!/bin/bash

cd /home/pi/chamosbot
source env/bin/activate
python3 /home/pi/chamosbot/chamos.py >> /home/pi/chamosbot/logs/$(python3 -c "import datetime;print(datetime.datetime.now().strftime('%Y%m%d'))").log &
